code/AzureMultiTenantApp.Web/Controllers/SyncController.cs
namespace Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Core.Storage;
    using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Models;
    using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Core.Services;

    [Authorize]
    public class SyncController : Controller
    {
        private readonly SyncStatusRepository syncStatusRepository;

        public SyncController()
            : this(new SyncStatusRepository())
        {
        }

        public SyncController(SyncStatusRepository syncStatusRepository)
        {
            this.syncStatusRepository = syncStatusRepository;
        }

        public ActionResult Index(string webSiteName)
        {
            if (string.IsNullOrWhiteSpace(webSiteName))
            {
                throw new ArgumentNullException("webSiteName");
            }

            var webSiteStatus = this.syncStatusRepository.RetrieveSyncStatus(webSiteName);
            var model = webSiteStatus
                .Where(s => s.IsOnline)
                .Select(s => new SyncStatusModel
                {
                    RoleInstanceId = s.RoleInstanceId,
                    Status = s.Status.ToString(),
                    SyncTimestamp = s.SyncTimestamp
                });

            this.ViewBag.WebSiteName = webSiteName;

            return View(model);
        }

        public ActionResult SyncChange(bool enable)
        {
            if (enable)
            {
                SyncService.SyncEnable();
            }
            else
            {
                SyncService.SyncDisable();
            }
            return RedirectToAction("Index", "WebSite");
        }
    }
}

code/AzureMultiTenantApp.Web/Controllers/WebSiteController.cs
namespace Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Web.Mvc;
    using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Core.Entities;
    using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Core.Storage;
    using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Models;
    using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Core.Services;

    [Authorize]
    public class WebSiteController : Controller
    {
        private readonly WebSiteRepository webSiteRepository;
        private readonly CertificateRepository certificateRepository;

        public WebSiteController()
            : this(new WebSiteRepository(), new CertificateRepository())
        {
        }

        public WebSiteController(WebSiteRepository webSiteRepository, CertificateRepository certificateRepository)
        {
            this.webSiteRepository = webSiteRepository;
            this.certificateRepository = certificateRepository;
        }

        public ActionResult Index()
        {
            var webSites = this.webSiteRepository.RetrieveWebSitesWithBindings();
            var model = webSites.Select(
                s => new WebSiteModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    Url = this.GetDefaultBindingUrl(s),
                    TestUrl = this.GetDefaultBindingTestUrl(s)
                });

            ViewBag.IsSyncEnabled = SyncService.IsSyncEnabled();
            
            return View("List", model);
        }

        public ActionResult Edit(Guid id)
        {
            var website = this.webSiteRepository.RetrieveWebSiteWithBindings(id);
            var model = new WebSiteModel
            {
                Id = website.Id,
                Name = website.Name,
                Description = website.Description,
                EnableTestChildApplication = website.EnableTestChildApplication,
                EnableCDNChildApplication = website.EnableCDNChildApplication,
                Bindings = website.Bindings.Select(b => new BindingModel
                {
                    Id = b.Id,
                    CertificateThumbprint = b.CertificateThumbprint,
                    HostName = b.HostName,
                    IpAddress = b.IpAddress,
                    Port = b.Port,
                    Protocol = b.Protocol,
                    WebSiteId = b.WebSiteId,
                    Url = this.GetBindingUrl(b)
                })
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Guid id, WebSiteModel model)
        {
            try
            {
                var site = new WebSite(id)
                {
                    Name = model.Name,
                    Description = model.Description,
                    EnableTestChildApplication = model.EnableTestChildApplication,
                    EnableCDNChildApplication = model.EnableCDNChildApplication,
                };

                this.webSiteRepository.UpdateWebSite(site);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        public ActionResult Create()
        {
            var model = new WebSiteCreateModel()
            {
                Protocol = "http",
                Port = 80,
                IpAddress = "*",
                Certificates = this.GetCertificatesList(),
                EnableTestChildApplication = true,
                EnableCDNChildApplication = true
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(WebSiteCreateModel model)
        {
            try
            {
                if (!this.ValidateDuplicatedSites(model.Name))
                {
                    model.Certificates = this.GetCertificatesList();
                    return View(model);
                }

                if (!this.ValidateDuplicatedBinding(model.HostName, model.Protocol, model.Port))
                {
                    model.Certificates = this.GetCertificatesList();
                    return View(model);
                }

                if (this.ValidateCertificateAndPort(model.CertificateThumbprint, model.Port, model.Protocol))
                {
                    var webSite = new WebSite()
                    {
                        Name = model.Name.Replace(" ", string.Empty).ToLowerInvariant(),
                        Description = model.Description,
                        EnableCDNChildApplication = model.EnableCDNChildApplication,
                        EnableTestChildApplication = model.EnableTestChildApplication
                    };

                    var binding = new Binding()
                    {
                        Port = model.Port,
                        Protocol = model.Protocol,
                        HostName = model.HostName,
                        IpAddress = model.IpAddress,
                        CertificateThumbprint = model.CertificateThumbprint
                    };

                    this.webSiteRepository.CreateWebSiteWithBinding(webSite, binding);

                    return RedirectToAction("Index");
                }
                else
                {
                    model.Certificates = this.GetCertificatesList();
                    return View(model);
                }
            }
            catch
            {
                model.Certificates = this.GetCertificatesList();
                return View(model);
            }
        }

        public ActionResult Delete(Guid id)
        {
            this.webSiteRepository.RemoveWebSite(id);

            return RedirectToAction("Index");
        }

        public ActionResult CreateBinding(Guid webSiteId)
        {
            var site = this.webSiteRepository.RetrieveWebSite(webSiteId);

            var model = new BindingModel()
            {
                WebSiteId = webSiteId,
                WebSiteName = site.Name,
                Protocol = "http",
                Port = 80,
                IpAddress = "*",
                CertificateThumbprint = null,
                Certificates = this.GetCertificatesList()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreateBinding(Guid webSiteId, BindingModel model)
        {
            try
            {
                if (!this.ValidateDuplicatedBinding(model.HostName, model.Protocol, model.Port))
                {
                    model.Certificates = this.GetCertificatesList();
                    return View(model);
                }

                if (this.ValidateCertificateAndPort(model.CertificateThumbprint, model.Port, model.Protocol))
                {
                    var binding = new Binding()
                    {
                        Port = model.Port,
                        Protocol = model.Protocol,
                        HostName = model.HostName,
                        IpAddress = model.IpAddress,
                        CertificateThumbprint = model.CertificateThumbprint
                    };

                    this.webSiteRepository.AddBindingToWebSite(webSiteId, binding);

                    return RedirectToAction("Edit", new { id = webSiteId });
                }
                else
                {
                    model.Certificates = this.GetCertificatesList();
                    return View(model);
                }
            }
            catch
            {
                model.Certificates = this.GetCertificatesList();
                return View(model);
            }
        }

        public ActionResult EditBinding(Guid id)
        {
            var binding = this.webSiteRepository.RetrieveBinding(id);
            var site = this.webSiteRepository.RetrieveWebSite(binding.WebSiteId);

            var model = new BindingModel()
            {
                WebSiteId = id,
                WebSiteName = site.Name,
                Protocol = binding.Protocol,
                IpAddress = binding.IpAddress,
                Port = binding.Port,
                HostName = binding.HostName,
                CertificateThumbprint = binding.CertificateThumbprint,
                Certificates = this.GetCertificatesList()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult EditBinding(Guid id, BindingModel model)
        {
            try
            {
                if (!this.ValidateDuplicatedBinding(model.HostName, model.Protocol, model.Port))
                {
                    model.Certificates = this.GetCertificatesList();
                    return View(model);
                }

                if (this.ValidateCertificateAndPort(model.CertificateThumbprint, model.Port, model.Protocol))
                {
                    Binding binding = this.webSiteRepository.RetrieveBinding(id);
                    binding.Port = model.Port;
                    binding.Protocol = model.Protocol;
                    binding.HostName = model.HostName;
                    binding.IpAddress = model.IpAddress;
                    binding.CertificateThumbprint = model.CertificateThumbprint;

                    this.webSiteRepository.UpdateBinding(binding);

                    return RedirectToAction("Edit", new { id = binding.WebSiteId });
                }
                else
                {
                    model.Certificates = this.GetCertificatesList();
                    return View(model);
                }
            }
            catch
            {
                model.Certificates = this.GetCertificatesList();
                return View(model);
            }
        }

        public ActionResult DeleteBinding(Guid id)

code/AzureMultiTenantApp.Web/Views/WebSite/Create.cshtml
@using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Extensions

@model Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Models.WebSiteCreateModel

@{
	ViewBag.Title = "New Web Site";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Web Site</h2>
<p>
	@Html.ActionLink("back to web sites list", "Index")
</p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
	@Html.ValidationSummary(true)
	
	<fieldset>
		<legend></legend>

		<div class="editor-label">
			@Html.LabelFor(model => model.Name)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.Name)
			@Html.ValidationMessageFor(model => model.Name)
		</div>

		<div class="editor-label">
			@Html.LabelFor(model => model.Description)
		</div>
		<div class="editor-field">
			@Html.TextAreaFor(model => model.Description, new { style = "width: 600px; height: 100px;" })
			@Html.ValidationMessageFor(model => model.Description)
		</div>
		
		<h3>Binding</h3>
		<div class="comment">
			Note: Only the ports 80 and 443 are open by default. If you want to enable another port in your Windows Azure Accelerator for Web Roles you need to add a new endpoint to your configuration and redeploy the package. See <a href="http://go.microsoft.com/fwlink/?LinkID=221048" target="_blank">here</a> for help.
		</div>

		<div class="editor-label">
			@Html.LabelFor(model => model.Protocol)
		</div>
		<div class="editor-field">
		   @* @Html.EditorFor(model => model.Protocol)*@
			@Html.DropDownListFor(model => model.Protocol, new SelectList(
							new string[] { "http", "https" }))
			@Html.DisplayHelpFor(model => model.Protocol, "HelpMessage")
			@Html.ValidationMessageFor(model => model.Protocol)
		</div>

		<div class="editor-label">
			@Html.LabelFor(model => model.Port)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.Port)
			@Html.DisplayHelpFor(model => model.Port, "HelpMessage")
			@Html.ValidationMessageFor(model => model.Port)
		</div>

@*        <div class="editor-label">
			@Html.LabelFor(model => model.IpAddress)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.IpAddress)
			@Html.DisplayHelpFor(model => model.IpAddress, "HelpMessage")
			@Html.ValidationMessageFor(model => model.IpAddress)
		</div>
*@
		<div class="editor-label">
			@Html.LabelFor(model => model.HostName)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.HostName)
			@Html.DisplayHelpFor(model => model.HostName, "HelpMessage")
			@Html.ValidationMessageFor(model => model.HostName)
		</div>

		<div class="editor-label">
			@Html.LabelFor(model => model.CertificateThumbprint)
		</div>
		<div class="editor-field">
			@Html.DropDownListFor(model => model.CertificateThumbprint, this.Model.Certificates, "Not Selected")
			@Html.DisplayHelpFor(model => model.CertificateThumbprint, "HelpMessage")
			@Html.ValidationMessageFor(model => model.CertificateThumbprint)
		</div>

		<div>
			@Html.EditorFor(model => model.EnableTestChildApplication)
			@Html.ValidationMessageFor(model => model.EnableTestChildApplication)
			<label for="EnableTestChildApplication">Enable test site</label>
			@Html.DisplayHelpFor(model => model.EnableTestChildApplication, "HelpMessage")
			<p style="font-size: 13px; font-style: italic;">Allows you to preview your site without setting up DNS entries at <a href="#">http://{yourhostedservice}.cloudapp.net/test/{sitename}</a></p>
		</div>

		<div>
			@Html.EditorFor(model => model.EnableCDNChildApplication)
			@Html.ValidationMessageFor(model => model.EnableCDNChildApplication)
			<label for="EnableTestChildApplication">Enable CDN</label>
			@Html.DisplayHelpFor(model => model.EnableCDNChildApplication, "HelpMessage")
			<p style="font-size: 13px; font-style: italic;">Enable CDN support for your site at <a href="#">http://{yourhostedservice}.cloudapp.net/cdn/{sitename}</a></p>
		</div>

		<p>
			<input type="image" value="Create" src="@Url.Content("~/Content/Create.png")" />
		</p>
	</fieldset>
}

<script type="text/javascript">
	jQuery(document).ready(function () {

		$("#Protocol").change(function () {
			var protocol = $.trim($("#Protocol").val()).toLowerCase();

			switch (protocol) {
				case "http":
					enableHttp();
					break;
				case "https":
					enableHttps();
					break;
				default:
					enableOther();
			}
		});

		$("#Protocol").change();
	});

	function enableHttp() {
		$("#CertificateId").val("");
		$("#Port").val("80");
		$("#CertificateId").attr("disabled", "disabled");
	}

	function enableHttps() {
		$("#Port").val("443");
		$("#CertificateId").attr("disabled", "");
	}

	function enableOther() {
		$("#CertificateId").val("");
		$("#HostName").val("");
		$("#Port").val("");
		$("#CertificateId").attr("disabled", "disabled");
	}
</script>

code/AzureMultiTenantApp.Web/Views/WebSite/CreateBinding.cshtml
@using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Extensions
@model Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Models.BindingModel
@{
    ViewBag.Title = "Add Binding to Web Site";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Add Binding to Web Site</h2>
<p>
    @Html.ActionLink("back to edit web site", "Edit", new { id = this.Model.WebSiteId })
</p>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
	
    <fieldset>
        <legend></legend>
        <div class="comment">
            Note: Only the ports 80 and 443 are open by default. If you want to enable another
            port in your Windows Azure Accelerator for Web Roles you need to add a new endpoint
            to your configuration and redeploy the package. See <a href="http://go.microsoft.com/fwlink/?LinkID=221048"
                target="_blank">here</a> for help.
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.WebSiteName)
        </div>
        <div class="editor-field">
            <span>@this.Model.WebSiteName</span>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Protocol)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Protocol, new SelectList(
                            new string[] { "http", "https" }))
            @*new string[] { "http", "https", "net.tcp", "net.pipe", "net.msmq", "msmq.formatname" }))*@
            @Html.DisplayHelpFor(model => model.Protocol, "HelpMessage")
            @Html.ValidationMessageFor(model => model.Protocol)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Port)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Port)
            @Html.DisplayHelpFor(model => model.Port, "HelpMessage")
            @Html.ValidationMessageFor(model => model.Port)
        </div>
        @*        <div class="editor-label">
			@Html.LabelFor(model => model.IpAddress)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.IpAddress)
			@Html.DisplayHelpFor(model => model.IpAddress, "HelpMessage")
			@Html.ValidationMessageFor(model => model.IpAddress)
		</div>
*@
        <div class="editor-label">
            @Html.LabelFor(model => model.HostName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HostName)
            @Html.DisplayHelpFor(model => model.HostName, "HelpMessage")
            @Html.ValidationMessageFor(model => model.HostName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CertificateThumbprint)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CertificateThumbprint, this.Model.Certificates, "Not Selected")
            @Html.DisplayHelpFor(model => model.CertificateThumbprint, "HelpMessage")
            @Html.ValidationMessageFor(model => model.CertificateThumbprint)
        </div>
        <p>
            <input type="image" value="Create" src="@Url.Content("~/Content/Create.png")" />
        </p>
    </fieldset>
}
<script type="text/javascript">
    jQuery(document).ready(function () {

        $("#Protocol").change(function () {
            var protocol = $.trim($("#Protocol").val()).toLowerCase();

            switch (protocol) {
                case "http":
                    enableHttp();
                    break;
                case "https":
                    enableHttps();
                    break;
                default:
                    enableOther();
            }
        });

        $("#Protocol").change();
    });

    function enableHttp() {
        $("#CertificateId").val("");
        $("#Port").val("80");
        $("#CertificateId").attr("disabled", "disabled");
    }

    function enableHttps() {
        $("#Port").val("443");
        $("#CertificateId").attr("disabled", "");
    }

    function enableOther() {
        $("#CertificateId").val("");
        $("#HostName").val("");
        $("#Port").val("");
        $("#CertificateId").attr("disabled", "disabled");
    }
</script>

code/AzureMultiTenantApp.Web/Views/WebSite/Edit.cshtml
@using Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Extensions
@model Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Models.WebSiteModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Edit Web Site</h2>
<p>
    @Html.ActionLink("back to web sites list", "Index")
</p>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    <fieldset>
        <legend></legend>
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Name)
        <div class="display-label">
            IIS Site Name
        </div>
        <div class="display-field">
            <span>
                @this.Model.Name
            </span>
        </div>
        <div class="display-label">
            Description
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { style = "width: 600px; height: 100px;" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div>
            @Html.EditorFor(model => model.EnableTestChildApplication)
            @Html.ValidationMessageFor(model => model.EnableTestChildApplication)
            <label for="EnableTestChildApplication">
                Enable test site</label>
            @Html.DisplayHelpFor(model => model.EnableTestChildApplication, "HelpMessage")
            <p style="font-size: 13px; font-style: italic;">
                Allows you to preview your site without setting up DNS entries at <a href="#">http://{yourhostedservice}.cloudapp.net/test/{sitename}</a></p>
        </div>
        <div>
            @Html.EditorFor(model => model.EnableCDNChildApplication)
            @Html.ValidationMessageFor(model => model.EnableCDNChildApplication)
            <label for="EnableTestChildApplication">
                Enable CDN</label>
            @Html.DisplayHelpFor(model => model.EnableCDNChildApplication, "HelpMessage")
            <p style="font-size: 13px; font-style: italic;">
                Enable CDN support for your site at <a href="#">http://{yourhostedservice}.cloudapp.net/cdn/{sitename}</a></p>
        </div>
        <p>
            <input type="image" value="Save" src="@Url.Content("~/Content/Save.png")" />
        </p>
    </fieldset>
}
<h3>
    Bindings</h3>
<p>
    @Html.ActionLink("add binding", "CreateBinding", new { webSiteId = Model.Id })
</p>
<table>
    <thead>
        <tr>
            <th>
                Protocol
            </th>
            @*            <th>IP Address</th>
*@
            <th>
                Port
            </th>
            <th>
                Host Name
            </th>
            <th>
                Certificate
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int k = 0;
            int nbindings = this.Model.Bindings.Count();
            foreach (var binding in this.Model.Bindings)
            {
                k++;
            <tr class="d@(k % 2)">
                <td class="left-aligned">
                    @binding.Protocol
                </td>
                @*                <td>
                    @binding.IpAddress
                </td>
*@
                <td>
                    @binding.Port
                </td>
                <td>
                    @if (string.IsNullOrEmpty(binding.Url))
                    {
                        @binding.HostName
                    }
                    else
                    {
                        <a href='@binding.Url'>@binding.HostName</a>
                    }
                </td>
                <td>
                    @if (!String.IsNullOrEmpty(binding.CertificateThumbprint))
                    { 
                        <text>N/A</text>
                    }
                    else
                    { 
                        @binding.CertificateThumbprint;
                    }
                </td>
                <td>
                    <a class="button-edit" href="/WebSite/EditBinding/@binding.Id" title="Edit"><span
                        class="ui-icon ui-icon-pencil" style="float: left;" /></a>
                    @if (k != 1 || nbindings != 1)
                    {
                        <a class="button-delete" href="/WebSite/DeleteBinding/@binding.Id" title="Delete"><span
                            class="ui-icon ui-icon-trash" style="float: left;" /></a>
                    }
                    else
                    { 
                        <span></span>
                    }
                </td>
            </tr>
            }
        }
    </tbody>
</table>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $(function () {
            $(".button-delete").click(function () {
                return confirm("Are you sure you wish to delete this item?");
            });
        });
    });
</script>

code/AzureMultiTenantApp.Web/Views/WebSite/List.cshtml
@model IEnumerable<Microsoft.Samples.DPE.AzureMultiTenantApp.Web.Models.WebSiteModel>
@{
    ViewBag.Title = "Web Sites";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Web Sites</h2>
<p>
    @Html.ActionLink("new web site", "Create") | @Html.ActionLink((ViewBag.IsSyncEnabled ? "disable sync" : "enable sync"), "SyncChange", "Sync", new { enable = !ViewBag.IsSyncEnabled }, new { })
</p>
@if (this.Model != null && this.Model.Count() > 0)
{
    <table>
        <tr>
            <th>
                IIS Site Name
            </th>
            <th>
                Description
            </th>
            <th>
                Preview
            </th>
            <th>
            </th>
        </tr>
        @{
    var i = 0;
        }
        @foreach (var item in this.Model)
        {
            i++;
    
            <tr class="d@(i % 2)">
                <td class="left-aligned">
                    @item.Name
                </td>
                <td class="left-aligned">
                    @item.Description
                </td>
                <td class="left-aligned" style="font-size: 13px">
                    Site: <a href='@item.Url'>@item.Url</a><br />
                    @if (item.TestUrl != null)
                    {
                        <span>Test site: <a href='@item.TestUrl'>@item.TestUrl</a></span>
                    }
                    else
                    {
                        <span>The test site is not enabled</span>
                    }
                </td>
                <td>
                    <a href="/WebSite/Edit/@item.Id" title="Edit"><span class="ui-icon ui-icon-pencil"
                        style="float: left; margin-left: 10px;" /></a><a class="button-delete" href="/WebSite/Delete/@item.Id" title="Delete">
                            <span class="ui-icon ui-icon-trash" style="float: left; margin-left: 10px;" />
                    </a><a href="/Sync?webSiteName=@item.Name" title="Status"><span class="ui-icon ui-icon-info"
                        style="float: left; margin-left: 10px;" /></a>
                </td>
            </tr>
        }
    </table>
}
else
{
    <div class="note">
        There are no web sites configured. Use the @Html.ActionLink("new web site", "Create")
        page to add a new web site to your Windows Azure Accelerator for Web Roles.
    </div>
}
<footer>
    @Html.Raw((!ViewBag.IsSyncEnabled ? "<br><div style='color:Red; font-weight:bold'>Synchronization is disabled. Enable Sync to resume site synchronization between role instances.</div>" : string.Empty))
</footer>
<script type="text/javascript">
    jQuery(document).ready(function () {
        $(function () {
            $(".button-delete").click(function () {
                return confirm("Are you sure you wish to delete this item?");
            });
        });
    });
</script>